--- #YAML:1.0
name:                Algorithm-Dependency-Objects
version:             0.04
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Carp:                          0
    Scalar::Util:                  1.10
    Set::Object:                   0
    Test::Deep:                    0
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
