---
name: Algorithm-Dependency-Objects
version: 0.01
author: ~
abstract: An implementation of an Object Dependency Algorithm
license: perl
requires:
  Carp: 0
  Scalar::Util: >= 1.10
  Set::Object: 0
  Test::More: >= .47
  perl: >= 5.008
provides:
  Algorithm::Dependency::Objects:
    file: lib/Algorithm/Dependency/Objects.pm
    version: 0.01
  Algorithm::Dependency::Objects::Ordered:
    file: lib/Algorithm/Dependency/Objects/Ordered.pm
    version: 0.01
generated_by: Module::Build version 0.261
